stages:
  - build
  - run

Building:
  stage: build
  script:
    - |
      #!/bin/bash
      npm run build
      docker build -t registry.gitlab.com/ioy.app/frontend .
      docker push registry.gitlab.com/ioy.app/frontend
  only:
    - develop
Running:
  stage: run
  script:
    - |
      echo "Success build"
  only:
    - develop

# stages:
#   - deploy_to_develop
#   - deploy_to_product

# deploy_to_develop:
#   stage: deploy_to_develop
#   script:
#     - |
#       #!/bin/bash
#       cd "$CI_DIR/repos" || exit
#       rm -rf $CI_PROJECT_NAME
#       git clone -b $CI_COMMIT_BRANCH $CI_REPOSITORY_URL
#       cd $CI_PROJECT_NAME
#       npm run docker:dev
#       cd "$CI_DIR" || exit
#       docker-compose -f $CI_CONFIG_DEVELOP up -d
#       docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#       docker push registry.lindaily.com/docdriver/notify:develop
#       docker pull $CI_CONTAINER_DEVELOP
#   only:
#     - develop
#     - /^v[0-9]+(?:.[0-9]+)+$/

# deploy_to_product:
#   stage: deploy_to_product
#   script:
#     - |
#       #!/bin/bash
#       cd "$CI_DIR/repos" || exit
#       rm -rf $CI_PROJECT_NAME
#       git clone -b $CI_COMMIT_BRANCH $CI_REPOSITORY_URL
#       cd $CI_PROJECT_NAME
#       npm run docker:product
#       cd "$CI_DIR" || exit
#       docker-compose -f $CI_CONFIG_PRODUCT up -d
#       docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#       docker push registry.lindaily.com/docdriver/notify:product
#       docker pull $CI_CONFIG_PRODUCT
#   only:
#     - master