stages:
  - build
  - run

Building:
  stage: build
  tags:
    - shell 
  script:
    - |
      #!/bin/bash
      docker build -t frontend .
  only:
    - develop
Running:
  stage: run
  tags:
    - shell 
  script:
    - |
      echo "Success build"
  only:
    - develop